<?php

/**
 * @file
 * Primary module hooks for Y LB Init Demo Pages.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function y_lb_init_demo_content_theme() : array {
  return [
    'menu__demo_main' => [
      'base hook' => 'menu',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function y_lb_init_demo_content_preprocess_block(&$variables) {
  // Set demo homepage and site name.
  if (in_array($variables['plugin_id'], ['ws_site_logo','ws_site_name'])) {
    $variables['content']['#front_page'] = Url::fromUserInput('/init-demo-home-page')->toString();
    // We don't have this variable in the ws_site_logo block.
    if (isset( $variables['content']['#site_name'])) {
      $variables['content']['#site_name'] = t('YMCA OF [SPRINGFIELD]');
    }
  }
}
