<?php

/**
 * @file
 * Installation file for Y LB Init Demo Pages.
 */

/**
 * y_lb_init_demo_content install.
 */
function y_lb_init_demo_content_install() {
  \Drupal::configFactory()->getEditable('system.site')->set('name', 'YMCA OF [SPRINGFIELD]')->save();
}

/**
 * y_lb_init_demo_content uninstall.
 */
function y_lb_init_demo_content_uninstall() {
  \Drupal::configFactory()->getEditable('system.site')->set('name', 'YMCA Website Services')->save();
}
